### ISSUE TITLE
"Use Data" and "Publish Data" aren't centered between pipes in header

### ISSUE THREAD

**Issue by robredpath** [IATI/design-system#20]
On https://iati.github.io/design-system/?path=/docs/layout-header--docs:

<img width="258" alt="Screenshot 2024-11-07 at 08 37 37" src="https://github.com/user-attachments/assets/52331542-d6bc-4f54-bfbd-2d82837f851c">

I think Contact isn't centred against the page edge as well but that probably matters less given that it's a full-width element

**Comment by tillywoodfield** [comment]
@robredpath I've fixed this so the spacing is now even: https://iati.github.io/design-system/?path=/docs/components-header--docs
