### ISSUE TITLE
Change CDN link to a valid link

### ISSUE THREAD

**Issue by notshi** [IATI/design-system#5]
**Brief Description**
I would like a simple way to use the suggested CDN link.

The current CDN link is an invalid link and would benefit from being a valid link.

Either of these would suffice. The non-min is preferable as it is more human-friendly and legible.

1. https://cdn.jsdelivr.net/npm/iati-design-system/dist/css/iati.min.css
2. https://cdn.jsdelivr.net/npm/iati-design-system/dist/css/iati.css

**Issue Location**
https://github.com/iati/design-system

**Comment by tillywoodfield** [comment]
Hi @notshi, a version number should be included in the CDN link, for example `https://cdn.jsdelivr.net/npm/iati-design-system@1/dist/css/iati.css`. It's fine to use either the expanded or minified CSS. The project is still in a relatively early stage so apologies for the current gaps in documentation, you can find the deployed Storybook at https://iati.github.io/design-system/, which shows the styles and components currently available in a more human-friendly way, along with code snippets.
